server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: catalog-route
          uri: lb:api-catalog-server
          predicates:
            - Path=/catalogs/**
        - id: movie-route
          uri: lb:api-movie-server
          predicates:
            - Path=/movies/**
  application:
    name: api-gateway-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway